export const INTEREST_OPTIONS = [
  { id: 'drama', labelKey: 'interestOptions.drama' },
  { id: 'lol', labelKey: 'interestOptions.lol' },
  { id: 'walking', labelKey: 'interestOptions.walking' },
  { id: 'escapeRoom', labelKey: 'interestOptions.escapeRoom' },
  { id: 'foodie', labelKey: 'interestOptions.foodie' },
  { id: 'gym', labelKey: 'interestOptions.gym' },
  { id: 'basketball', labelKey: 'interestOptions.basketball' },
  { id: 'cooking', labelKey: 'interestOptions.cooking' },
  { id: 'music', labelKey: 'interestOptions.music' },
  { id: 'movies', labelKey: 'interestOptions.movies' },
  { id: 'travel', labelKey: 'interestOptions.travel' },
  { id: 'reading', labelKey: 'interestOptions.reading' },
  { id: 'photography', labelKey: 'interestOptions.photography' },
  { id: 'cafe', labelKey: 'interestOptions.cafe' },
  { id: 'soccer', labelKey: 'interestOptions.soccer' },
  { id: 'tennis', labelKey: 'interestOptions.tennis' },
  { id: 'yoga', labelKey: 'interestOptions.yoga' },
  { id: 'hiking', labelKey: 'interestOptions.hiking' },
  { id: 'gaming', labelKey: 'interestOptions.gaming' },
  { id: 'kpop', labelKey: 'interestOptions.kpop' },
  { id: 'anime', labelKey: 'interestOptions.anime' },
  { id: 'pets', labelKey: 'interestOptions.pets' },
  { id: 'dance', labelKey: 'interestOptions.dance' },
  { id: 'cycling', labelKey: 'interestOptions.cycling' },
  { id: 'running', labelKey: 'interestOptions.running' },
  { id: 'baking', labelKey: 'interestOptions.baking' },
  { id: 'wine', labelKey: 'interestOptions.wine' },
  { id: 'shopping', labelKey: 'interestOptions.shopping' },
] as const;

export const MAX_INTERESTS = 10;
