export const INTEREST_SECTIONS = [
  {
    id: 'content',
    titleKey: 'interestSections.content',
    items: [
      { id: 'drama', labelKey: 'interestOptions.drama' },
      { id: 'movies', labelKey: 'interestOptions.movies' },
      { id: 'anime', labelKey: 'interestOptions.anime' },
      { id: 'youtube', labelKey: 'interestOptions.youtube' },
      { id: 'webtoon', labelKey: 'interestOptions.webtoon' },
      { id: 'variety', labelKey: 'interestOptions.variety' },
      { id: 'documentary', labelKey: 'interestOptions.documentary' },
      { id: 'thriller', labelKey: 'interestOptions.thriller' },
      { id: 'romance', labelKey: 'interestOptions.romance' },
      { id: 'scifi', labelKey: 'interestOptions.scifi' },
    ],
  },
  {
    id: 'games',
    titleKey: 'interestSections.games',
    items: [
      { id: 'gaming', labelKey: 'interestOptions.gaming' },
      { id: 'lol', labelKey: 'interestOptions.lol' },
      { id: 'overwatch', labelKey: 'interestOptions.overwatch' },
      { id: 'valorant', labelKey: 'interestOptions.valorant' },
      { id: 'pubg', labelKey: 'interestOptions.pubg' },
      { id: 'minecraft', labelKey: 'interestOptions.minecraft' },
      { id: 'roblox', labelKey: 'interestOptions.roblox' },
      { id: 'genshin', labelKey: 'interestOptions.genshin' },
      { id: 'mobileGame', labelKey: 'interestOptions.mobileGame' },
      { id: 'nintendo', labelKey: 'interestOptions.nintendo' },
      { id: 'playstation', labelKey: 'interestOptions.playstation' },
      { id: 'rpg', labelKey: 'interestOptions.rpg' },
      { id: 'fps', labelKey: 'interestOptions.fps' },
      { id: 'simulation', labelKey: 'interestOptions.simulation' },
    ],
  },
  {
    id: 'outdoor',
    titleKey: 'interestSections.outdoor',
    items: [
      { id: 'cafe', labelKey: 'interestOptions.cafe' },
      { id: 'walking', labelKey: 'interestOptions.walking' },
      { id: 'foodie', labelKey: 'interestOptions.foodie' },
      { id: 'escapeRoom', labelKey: 'interestOptions.escapeRoom' },
      { id: 'bar', labelKey: 'interestOptions.bar' },
      { id: 'camping', labelKey: 'interestOptions.camping' },
      { id: 'travel', labelKey: 'interestOptions.travel' },
      { id: 'shopping', labelKey: 'interestOptions.shopping' },
      { id: 'driving', labelKey: 'interestOptions.driving' },
      { id: 'picnic', labelKey: 'interestOptions.picnic' },
      { id: 'karaoke', labelKey: 'interestOptions.karaoke' },
      { id: 'cinema', labelKey: 'interestOptions.cinema' },
      { id: 'concert', labelKey: 'interestOptions.concert' },
      { id: 'exhibition', labelKey: 'interestOptions.exhibition' },
      { id: 'festival', labelKey: 'interestOptions.festival' },
    ],
  },
  {
    id: 'indoor',
    titleKey: 'interestSections.indoor',
    items: [
      { id: 'reading', labelKey: 'interestOptions.reading' },
      { id: 'cooking', labelKey: 'interestOptions.cooking' },
      { id: 'baking', labelKey: 'interestOptions.baking' },
      { id: 'drawing', labelKey: 'interestOptions.drawing' },
      { id: 'bingeWatch', labelKey: 'interestOptions.bingeWatch' },
      { id: 'boardGame', labelKey: 'interestOptions.boardGame' },
      { id: 'homeCafe', labelKey: 'interestOptions.homeCafe' },
      { id: 'gardening', labelKey: 'interestOptions.gardening' },
      { id: 'writing', labelKey: 'interestOptions.writing' },
      { id: 'puzzle', labelKey: 'interestOptions.puzzle' },
      { id: 'homeWorkout', labelKey: 'interestOptions.homeWorkout' },
      { id: 'knitting', labelKey: 'interestOptions.knitting' },
      { id: 'candleMaking', labelKey: 'interestOptions.candleMaking' },
      { id: 'diy', labelKey: 'interestOptions.diy' },
      { id: 'teaCeremony', labelKey: 'interestOptions.teaCeremony' },
    ],
  },
  {
    id: 'sports',
    titleKey: 'interestSections.sports',
    items: [
      { id: 'gym', labelKey: 'interestOptions.gym' },
      { id: 'yoga', labelKey: 'interestOptions.yoga' },
      { id: 'pilates', labelKey: 'interestOptions.pilates' },
      { id: 'running', labelKey: 'interestOptions.running' },
      { id: 'cycling', labelKey: 'interestOptions.cycling' },
      { id: 'hiking', labelKey: 'interestOptions.hiking' },
      { id: 'swimming', labelKey: 'interestOptions.swimming' },
      { id: 'climbing', labelKey: 'interestOptions.climbing' },
      { id: 'basketball', labelKey: 'interestOptions.basketball' },
      { id: 'soccer', labelKey: 'interestOptions.soccer' },
      { id: 'tennis', labelKey: 'interestOptions.tennis' },
      { id: 'badminton', labelKey: 'interestOptions.badminton' },
      { id: 'bowling', labelKey: 'interestOptions.bowling' },
      { id: 'golf', labelKey: 'interestOptions.golf' },
      { id: 'dance', labelKey: 'interestOptions.dance' },
    ],
  },
  {
    id: 'music',
    titleKey: 'interestSections.music',
    items: [
      { id: 'music', labelKey: 'interestOptions.music' },
      { id: 'kpop', labelKey: 'interestOptions.kpop' },
      { id: 'jpop', labelKey: 'interestOptions.jpop' },
      { id: 'pop', labelKey: 'interestOptions.pop' },
      { id: 'hiphop', labelKey: 'interestOptions.hiphop' },
      { id: 'ballad', labelKey: 'interestOptions.ballad' },
      { id: 'indie', labelKey: 'interestOptions.indie' },
      { id: 'rock', labelKey: 'interestOptions.rock' },
      { id: 'rnb', labelKey: 'interestOptions.rnb' },
      { id: 'jazz', labelKey: 'interestOptions.jazz' },
    ],
  },
  {
    id: 'etc',
    titleKey: 'interestSections.etc',
    items: [
      { id: 'photography', labelKey: 'interestOptions.photography' },
      { id: 'pets', labelKey: 'interestOptions.pets' },
      { id: 'wine', labelKey: 'interestOptions.wine' },
      { id: 'coffee', labelKey: 'interestOptions.coffee' },
      { id: 'meditation', labelKey: 'interestOptions.meditation' },
      { id: 'selfDev', labelKey: 'interestOptions.selfDev' },
      { id: 'languageLearn', labelKey: 'interestOptions.languageLearn' },
      { id: 'fashion', labelKey: 'interestOptions.fashion' },
      { id: 'beauty', labelKey: 'interestOptions.beauty' },
      { id: 'tattoo', labelKey: 'interestOptions.tattoo' },
      { id: 'cosplay', labelKey: 'interestOptions.cosplay' },
      { id: 'perfume', labelKey: 'interestOptions.perfume' },
      { id: 'mbti', labelKey: 'interestOptions.mbti' },
      { id: 'astrology', labelKey: 'interestOptions.astrology' },
      { id: 'tarot', labelKey: 'interestOptions.tarot' },
    ],
  },
] as const;

// `flatMap` over a `readonly`-tagged tuple of sections trips up TS5's tuple
// element inference (it tries to widen each section to a single union member
// rather than to "an array of union members"). Annotating the result as a
// readonly array of the common shape sidesteps that.
export type InterestOption = { readonly id: string; readonly labelKey: string };
export const INTEREST_OPTIONS: readonly InterestOption[] = INTEREST_SECTIONS.flatMap(
  (s) => [...s.items],
);

export const MAX_INTERESTS = 10;
